CREATE USER mockitoUser identified by mockito;
GRANT ALL PRIVILEGES TO mockitoUser;
--================================================
CREATE TABLE employee_table (
                                employee_id NUMBER(11)  GENERATED BY DEFAULT ON NULL AS IDENTITY,
                                employee_name NVARCHAR2(60) NOT NULL,
                                email NVARCHAR2(45) NOT NULL,
                                salary NUMBER(10,2) default NULL,
                                date_of_joining DATE default NULL,
                                bonus decimal(10,0) default NULL,
                                PRIMARY KEY  (employee_id)
) ;
--========================================================
INSERT INTO employee_table(employee_name,email,salary,date_of_joining,bonus)
VALUES('Paul','paul.cs2009@yahoo.com',60000.00000,SYSDATE,400.00);